### ISSUE TITLE
logo for Camera2-API-Based-Camera-App

### ISSUE THREAD

**Issue by hafizahmmed** [imcgeek/Android-Camera-App#1]
Hello,
Good Day, i make a logo icon for your project. If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project.

![camera2 api-01](https://user-images.githubusercontent.com/38810169/42500446-2c0a4324-8453-11e8-966b-d374b9a5c970.jpg)

**Comment by imcgeek** [comment]
Thanks for the connecting to contribute to this open source project. request you to take a pull copy of the repo and replace the app icon to your logo for this project and send the request to merge it.

**Comment by hafizahmmed** [comment]
thank you sir 

what is your app name ??

**Comment by imcgeek** [comment]
Welcome @hafizahmmed ! I love it your approach to contributing to open-source project. #keepContributingToOpenSource.

I have made this project to deal with CAMERA2-API so that point of time, i kept name of this project is Camera App, You can check out the String.xml and rename it, if you have suggestion of name to this app.

**Comment by hafizahmmed** [comment]
ok give me the size requirement for the icon.

**Comment by imcgeek** [comment]
48 × 48 (mdpi)
72 × 72 (hdpi) 
96 × 96 (xhdpi) 
144 × 144 (xxhdpi) 
192 × 192 (xxxhdpi)

**Comment by hafizahmmed** [comment]
please check #2

when you update apps code??

**Comment by imcgeek** [comment]
I have reviewed you commit, excellent work was done by @hafizahmmed! I will share my previous few project and upcoming project if they required the logo.

**Comment by hafizahmmed** [comment]
thankyou sir i need new project for work.

**Comment by imcgeek** [comment]
App code is updated with icon and app theme.
